temporarily disable nightly

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,18 +16,18 @@ matrix:
   include:
     # Nightly builds run the tests/examples end-to-end test suite.
     # Does not include Windows since Projects/Models are mostly not compatible with Windows as of now.
-    - stage: Nightly
-    - language: python
-      python: 2.7
-      install:
-        # CHANGED_FILES detects whether or not files related to the nightly build are changed.
-        # True is so that the command returns a 0 exit code whether or not CHANGED_FILES is empty.
-        - CHANGED_FILES=$(git diff --name-only master..HEAD | grep "tests/examples\|examples\|Dockerfile") || true;
-        - if [[ "$TRAVIS_EVENT_TYPE" == "cron" || ! -z "$CHANGED_FILES" ]]; then
-            INSTALL_LARGE_PYTHON_DEPS=true source ./travis/install-common-deps.sh;
-          fi;
-      script:
-        - ./travis/stage-python2-nightly.sh
+#    - stage: Nightly
+#    - language: python
+#      python: 2.7
+#      install:
+#        # CHANGED_FILES detects whether or not files related to the nightly build are changed.
+#        # True is so that the command returns a 0 exit code whether or not CHANGED_FILES is empty.
+#        - CHANGED_FILES=$(git diff --name-only master..HEAD | grep "tests/examples\|examples\|Dockerfile") || true;
+#        - if [[ "$TRAVIS_EVENT_TYPE" == "cron" || ! -z "$CHANGED_FILES" ]]; then
+#            INSTALL_LARGE_PYTHON_DEPS=true source ./travis/install-common-deps.sh;
+#          fi;
+#      script:
+#        - ./travis/stage-python2-nightly.sh
     - stage: small
       if: type != cron
 #    - language: python
