Run `mleap` tests in cross version testing (#4797)
* Install mleap in run-python-sagemaker-tests

Signed-off-by: harupy <hkawamura0130@gmail.com>

* move test file under tests/mleap

Signed-off-by: harupy <hkawamura0130@gmail.com>

* use cross version test

Signed-off-by: harupy <hkawamura0130@gmail.com>

* ignore tests/mleap

Signed-off-by: harupy <hkawamura0130@gmail.com>

* bump

Signed-off-by: harupy <hkawamura0130@gmail.com>

* remove mleap from setup.py

Signed-off-by: harupy <hkawamura0130@gmail.com>

* update pylintrc

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix jars

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix typo

Signed-off-by: harupy <hkawamura0130@gmail.com>

* exclude f2j

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix version

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix isinstance

Signed-off-by: harupy <hkawamura0130@gmail.com>

* comma

Signed-off-by: harupy <hkawamura0130@gmail.com>

* comment

Signed-off-by: harupy <hkawamura0130@gmail.com>

* lint

Signed-off-by: harupy <hkawamura0130@gmail.com>

diff --git a/mlflow/ml-package-versions.yml b/mlflow/ml-package-versions.yml
--- a/mlflow/ml-package-versions.yml
+++ b/mlflow/ml-package-versions.yml
@@ -349,3 +349,24 @@ spark:
         ./dev/setup-spark-datasource-autologging.sh
         find tests/spark_autologging/datasource -name 'test*.py' | xargs -L 1 pytest --large
       fi
+
+mleap:
+  package_info:
+    pip_release: "mleap"
+
+  models:
+    minimum: "0.15.0"
+    maximum: "0.18.0"
+    requirements:
+      "<= 0.17.0": ["pyspark==2.4.5"]
+      "> 0.17.0": ["pyspark==3.0.2"]
+    run: |
+      SAGEMAKER_OUT=$(mktemp)
+      if mlflow sagemaker build-and-push-container --no-push --mlflow-home . > $SAGEMAKER_OUT 2>&1; then
+        echo "Sagemaker container build succeeded.";
+      else
+        echo "Sagemaker container build failed, output:";
+        cat $SAGEMAKER_OUT;
+        exit 1
+      fi
+      pytest tests/mleap/test_mleap_model_export.py --large
