Add spark model export tests in cross version tests (#4247)
* Add spark model export tests in cross version tests

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* Add sklearn

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* add pyarrow

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* build docker image

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* fix

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* fix indent

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* trigger ci

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* remove useless comment

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

* Add exit 1

Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

diff --git a/mlflow/ml-package-versions.yml b/mlflow/ml-package-versions.yml
--- a/mlflow/ml-package-versions.yml
+++ b/mlflow/ml-package-versions.yml
@@ -272,3 +272,22 @@ statsmodels:
     maximum: "0.12.2"
     run: |
       pytest tests/statsmodels/test_statsmodels_autolog.py --large
+
+spark:
+  package_info:
+    pip_release: "pyspark"
+
+  models:
+    minimum: "3.0.0"
+    maximum: "3.1.1"
+    requirements: ["boto3", "scikit-learn", "pyarrow"]
+    run: |
+      SAGEMAKER_OUT=$(mktemp)
+      if mlflow sagemaker build-and-push-container --no-push --mlflow-home . > $SAGEMAKER_OUT 2>&1; then
+        echo "Sagemaker container build succeeded.";
+      else
+        echo "Sagemaker container build failed, output:";
+        cat $SAGEMAKER_OUT;
+        exit 1
+      fi
+      pytest --verbose tests/spark --large --ignore tests/spark/test_mleap_model_export.py
