Replace deprecated sqlalchemy features that will be removed in sqlalchemy 2.0 (#7061)
* sqlalchemy 2.0.0b1

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Fix job name

Signed-off-by: harupy <hkawamura0130@gmail.com>

* use sql.text

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Fix tests

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Fix failed tests

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Use SQLALCHEMY_WARN_20

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Override filterwarnings in database job

Signed-off-by: harupy <hkawamura0130@gmail.com>

* fix

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Add slash

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Run tests with SQLAlchemy 2.x

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Use variable

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Remove filterwarnings override

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Fix version

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Skip test_schema_is_up_to_date

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Install sqlalchemy from github

Signed-off-by: harupy <hkawamura0130@gmail.com>

* Fix max length

Signed-off-by: harupy <hkawamura0130@gmail.com>

Signed-off-by: harupy <hkawamura0130@gmail.com>

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -140,6 +140,32 @@ jobs:
         done
 
         test $err = 0
+    - name: Rebuild images with SQLAlchemy 2.x
+      run: |
+        sed -i '/sqlalchemy.*/d' requirements/core-requirements.txt
+        # https://github.com/sqlalchemy/sqlalchemy/commit/f4214975a7deb5e13f8b6cf21e39697821396a7f
+        # is a patch for https://github.com/sqlalchemy/sqlalchemy/issues/8661. Tests that log a tag
+        # with a long value (e.g. `"a" * 5000`) fail because of this issue. Install sqlalchemy from
+        # this commit until a new 2.x version is published on PyPI.
+        echo 'sqlalchemy@git+https://github.com/sqlalchemy/sqlalchemy.git@f4214975a7deb5e13f8b6cf21e39697821396a7f' >> requirements/core-requirements.txt
+        git diff
+        ./tests/db/compose.sh build --build-arg DEPENDENCIES="$(python setup.py -q dependencies)"
+    - name: Run tests
+      run: |
+        set +e
+        err=0
+        trap 'err=1' ERR
+
+        for service in $(./tests/db/compose.sh config --services | grep '^mlflow-')
+        do
+          # Set `--no-TTY` to show container logs on GitHub Actions:
+          ./tests/db/compose.sh run --rm --no-TTY $service pytest \
+            tests/store/tracking/test_sqlalchemy_store.py \
+            tests/store/model_registry/test_sqlalchemy_store.py \
+            tests/db
+        done
+
+        test $err = 0
     - name: Clean up
       run: |
         ./tests/db/compose.sh down --volumes --remove-orphans --rmi all
