Emit a warning if test fail on an unsupported version
Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

diff --git a/.github/workflows/sklearn.yml b/.github/workflows/sklearn.yml
--- a/.github/workflows/sklearn.yml
+++ b/.github/workflows/sklearn.yml
@@ -48,6 +48,14 @@ jobs:
         run: |
           python -c "$COMMAND"
       - name: Run tests
+        id: run-tests
         continue-on-error: ${{ steps.check-version.outputs.supported != 'True' }}
+        env:
+          SUPPORTED: steps.check-version.outputs.supported
         run: |
           pytest --verbose tests/sklearn/test_sklearn_autolog.py --large
+
+          # Emit a warning if the tests fail on an unsupported version
+          if [[ "$SUPPORTED" == "True" &&  "$?" != "0" ]]; then
+            echo "::warning ::tests failed"
+          fi
